name: 'action-generate-release-name'
description: 'Generate release name'
author: 'Alex Shemshurenko'
inputs:
  pkg_json_path: 
    required: true
    description: 'path to package.json of the electron package'
  branch_name: 
    required: true
    description: 'branch name'
  sha: 
    required: true
    description: 'sha of the commit'  
  name_appendix: 
    required: false
    description: 'custom name appendix'
    defualt: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: upload-cloud
  color: blue
