name: 'test'
on: push

jobs:
  run-build-and-test: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm ci
      - run: |
          npm run test
        env:
          GITHUB_TOKEN: ${{ github.token }}
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: run-the-action
        with:
          base_name: 'my-base-name'
          pkg_json_path: 'test/fixtures/package.json'
          branch_name: 'branch-name'
          sha: 123abf
      - name:
        if: ${{ steps.run-the-action.outputs.result != my-base-name-0.0.1-branch-name-123abf }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('failed to generate result name correctly ${{steps.run-the-action.outputs.result}} != my-base-name-0.0.1-branch-name-123abf')
